version: '3'

services:
  redis:
    image: redis:3.2.8-alpine
    volumes:
    - /root/data/redis:/data
    ports:
    - "6379:6379"
  mongo:
    image: mongo:3.4
    volumes:
    - /root/data/db:/data/db
    ports:
    - "27017:27017"
